@echo off

set NO_INTERACTION=1
set REPORT_EXIT_STATUS=1
set SKIP_IO_CAPTURE_TESTS=1
set TEST_PHP_EXECUTABLE=%APPVEYOR_BUILD_FOLDER%\bin\php.exe

"%TEST_PHP_EXECUTABLE%" %APPVEYOR_BUILD_FOLDER%\run-tests.php --show-diff

exit /b %EXIT_CODE%

